# Generated by Django 5.2 on 2025-05-01 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('profile_picture', models.ImageField(default='default_profile_pic.png', null=True, upload_to='profile_pics/')),
                ('bio', models.TextField(blank=True, max_length=500)),
            ],
        ),
    ]
