# Generated by Django 5.2 on 2025-05-03 22:57

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='default_profile_pic.png', upload_to=core.models.user_profile_pic_path),
        ),
    ]
